# Generated by Django 3.2.9 on 2021-12-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_browse', '0009_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(max_length=200, verbose_name='Импринт'),
        ),
    ]
