# Generated by Django 3.2.9 on 2021-12-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_browse', '0011_alter_bookinstance_due_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Поддержка'), ('o', 'Забронирована'), ('a', 'Свободная'), ('r', 'Занята')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
