# Generated by Django 3.2.9 on 2021-12-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_browse', '0010_alter_bookinstance_imprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возвращения'),
        ),
    ]
